spring.application.name=sap-ccv2-devops-mcp-server
server.port=8085
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.name=mcp-sap-ccv2-devops
sap.ccv2.api.subscriptionCode=94d768421b0a4e1289dd1d77186cb51a
sap.ccv2.api.applicationCode=commerce-cloud
sap.ccv2.api.token=5db83b2ad7447c13f78952119fc