spring.application.name=sap-ccv2-devops-mcp-server
spring.ai.openai.model=gpt-4o
spring.ai.openai.api-key=
api.telegram.token=
spring.ai.mcp.client.streamable-http.connections.mymcpserver.url=http://localhost:8085/mcp
allowed.client.ids=22222222,111111111