spring.application.name=sap-ccv2-devops-mcp-server
server.port=8085
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.name=mcp-sap-ccv2-devops
sap.ccv2.api.subscriptionCode=
sap.ccv2.api.applicationCode=commerce-cloud
sap.ccv2.api.token=